name: Update Vue LSP to latest version
on:
  schedule:
    - cron: "0 0,12 * * *"
jobs:
  update_vue_lsp_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get latest version of Vue LSP
        id: get_vue_lsp_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: vuejs/language-tools
          excludes: prerelease, draft
      - name: Versions
        id: versions
        env:
          LATEST_FULL: ${{ steps.get_vue_lsp_version.outputs.release }}
        run: |
          current=$(grep -oP '(?<=^const PACKAGE_VERSION: &str = ")([\d\.]+)(?=";$)' src/vue.rs)
          echo "current=$current" >> $GITHUB_OUTPUT
          latest=$(echo $LATEST_FULL | cut -d 'v' -f2)
          echo "latest=$latest" >> $GITHUB_OUTPUT
      - name: Change version
        if: steps.versions.outputs.current != steps.versions.outputs.latest
        env:
          CURRENT: ${{ steps.versions.outputs.current }}
          LATEST: ${{ steps.versions.outputs.latest }}
        run: |
          # Change version string
          sed -i -E "s/(const PACKAGE_VERSION: &str = \")($CURRENT)(\";)/\1$LATEST\3/" src/vue.rs

          # Bump extension verison
          ext=$(grep -oP '(?<=^version = ")([\d\.]+)(?="$)' Cargo.toml )
          IFS=. read -r major minor patch <<< $ext
          ((patch++))
          new_ext="$major.$minor.$patch"
          sed -i -E "0,/(version = \")($ext)(\")/s//\1$new_ext\3/" Cargo.toml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update `@vue/language-server` from `${{ steps.versions.outputs.current }}` to `${{ steps.versions.outputs.latest }}`"
          title: Update `@vue/language-server` from `${{ steps.versions.outputs.current }}` to `${{ steps.versions.outputs.latest }}`
          body: |
            Update [`@vue/language-server`][1] from `${{ steps.versions.outputs.current }}` to `${{ steps.versions.outputs.latest }}`

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/vuejs/language-tools
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: chore/bump-vue-lsp-to-${{ steps.versions.outputs.latest }}
